services:
  frontend:
    container_name: mspr3-frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    restart: always
    depends_on:
      - backend
    networks:
      - mspr3-network

  backend:
    container_name: mspr3-backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    restart: always
    depends_on:
      - db
    networks:
      - mspr3-network
  ai-api:
    container_name: mspr3-ai
    build:
      context: ./ai-api
      dockerfile: ai.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./ai-api/app:/code/app
    restart: always
    depends_on:
      - backend
      - db
    networks:
      - mspr3-network

  db:
    container_name: mspr3-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mspr3-network

volumes:
  pgdata:
    name: mspr3-pgdata

networks:
  mspr3-network:
    driver: bridge
