services:
  frontend:
    container_name: mspr3-frontend-prod
    image: ${DOCKERHUB_USERNAME}/mspr3-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    environment:
      - NODE_ENV=production
      - SERVER_NAME=${SERVER_NAME}
    restart: always
    networks:
      - mspr3-network

  backend:
    container_name: mspr3-backend-prod
    image: ${DOCKERHUB_USERNAME}/mspr3-backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: always
    networks:
      - mspr3-network

  ai-api:
    container_name: mspr3-ai-prod
    image: ${DOCKERHUB_USERNAME}/mspr3-ai-api:latest
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: always
    networks:
      - mspr3-network

  db:
    container_name: mspr3-db-prod
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - mspr3-db-data:/var/lib/postgresql/data
    networks:
      - mspr3-network
    restart: always

volumes:
  mspr3-db-data:

networks:
  mspr3-network:
    driver: bridge
