services:
  frontend:
    container_name: mspr3-frontend-prod
    image: ${DOCKERHUB_USERNAME}/mspr3-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    restart: always
    depends_on:
      - backend
    networks:
      - mspr3-network
    volumes:
      - ./certs:/etc/nginx/certs:ro

  backend:
    container_name: mspr3-backend-prod
    image: ${DOCKERHUB_USERNAME}/mspr3-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: always
    depends_on:
      - db
    networks:
      - mspr3-network

  ai-api:
    container_name: mspr3-ai-prod
    image: ${DOCKERHUB_USERNAME}/mspr3-ai-api:latest
    ports:
      - "8000:80"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: always
    depends_on:
      - backend
      - db
    networks:
      - mspr3-network

  db:
    container_name: mspr3-db-prod
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - mspr3-network
    restart: always

volumes:
  pgdata_prod:
    name: mspr3-pgdata-prod

networks:
  mspr3-network:
    driver: bridge
