name: Generate Changelog

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Configure Git
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

      - name: Generate Changelog
        run: |
          rm -f CHANGELOG.md
          conventional-changelog -p angular -o CHANGELOG.md -r 0
          
          awk '
          /^\* / {
              match($0, /\* (.+) \([a-f0-9]+\)/, arr)
              msg = arr[1]
              if (!seen[msg]++) print $0
          }
          !/^\* / { print $0 }
          ' CHANGELOG.md > temp.md && mv temp.md CHANGELOG.md


      - name: Commit and Push
        run: |
          git add CHANGELOG.md
          git diff --staged --quiet || (git commit -m "docs: update changelog" && git push)