name: Documentation

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc, LaTeX, Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

      - name: Prepare directories
        run: |
          mkdir -p pdf

      - name: Convert all Markdown files to individual PDFs
        run: |
          find docs/ -name '*.md' | while read file; do
            relpath="${file#docs/}"
            filename="${relpath//\//_}"
            filename="${filename%.md}"
            pandoc "$file" \
              -o "pdf/$filename.pdf" \
              --pdf-engine=xelatex \
              --template=docs/latex/azure-mui-template.tex \
              --toc \
              --toc-depth=2 \
              --metadata title="Documentation Section"
          done

      - name: Convert PNG images to PDF (Annex)
        run: |
          mkdir -p pdf/annexes
          find docs/ -name '*.png' | while read img; do
            name=$(basename "$img" .png)
            convert "$img" "pdf/annexes/$name.pdf"
          done

      - name: Create combined Markdown master file
        run: |
          echo "" > combined.md
          
          # Ordre personnalisé
          cat docs/brief1.md >> combined.md
          cat docs/brief2.md >> combined.md
          
          find docs/benchmark -name '*.md' | sort | while read f; do cat "$f" >> combined.md; done
          find docs/architecture -name '*.md' | sort | while read f; do cat "$f" >> combined.md; done
          cat docs/tech-stack.md >> combined.md

          # Ajouter les autres .md restants
          find docs/ -name '*.md' | grep -v -E 'brief1|brief2|benchmark|architecture|tech-stack' | sort | while read f; do
            cat "$f" >> combined.md
          done

          # Ajouter les images converties
          echo "# Annexes" >> combined.md
          find pdf/annexes -name '*.pdf' | sort | while read annex; do
            echo "\\includepdf[pages=-]{$annex}" >> combined.md
          done

      - name: Fix \tightlist if needed
        run: |
          echo "\providecommand{\tightlist}{}" | cat - combined.md > tmp && mv tmp combined.md

      - name: Generate Master PDF
        run: |
          pandoc combined.md \
            -o pdf/documentation.pdf \
            --pdf-engine=xelatex \
            --template=docs/latex/azure-mui-template.tex \
            --toc \
            --toc-depth=2 \
            --metadata title="Documentation"

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: pdf/
