name: Documentation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc, LaTeX, and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra imagemagick

      - name: Prepare folders
        run: |
          mkdir -p pdf site

      - name: Generate combined.md
        run: |
          echo "" > combined.md

          # Ajout des fichiers dans l'ordre souhaité
          cat docs/brief_part1.md >> combined.md
          echo "\n\n---\n\n" >> combined.md
          cat docs/brief_part2.md >> combined.md
          echo "\n\n---\n\n" >> combined.md

          find docs/benchmark -name '*.md' | sort | while read file; do
            cat "$file" >> combined.md
            echo "\n\n---\n\n" >> combined.md
          done

          find docs/architecture -name '*.md' | sort | while read file; do
            cat "$file" >> combined.md
            echo "\n\n---\n\n" >> combined.md
          done

          [ -f docs/tech-stack.md ] && cat docs/tech-stack.md >> combined.md && echo "\n\n---\n\n" >> combined.md

          find docs/ -name '*.md' \
            ! -path 'docs/brief_part1.md' \
            ! -path 'docs/brief_part2.md' \
            ! -path 'docs/benchmark/*' \
            ! -path 'docs/architecture/*' \
            ! -path 'docs/tech-stack.md' \
            | sort | while read file; do
              cat "$file" >> combined.md
              echo "\n\n---\n\n" >> combined.md
            done

          echo "# Annexes" >> combined.md
          echo "Voir les images en bas de cette page." >> combined.md

      - name: Convert images to PDF for appendix
        run: |
          mkdir -p pdf/appendices
          find docs/ -type f \( -iname "*.png" -o -iname "*.jpg" \) | while read img; do
            convert "$img" "pdf/appendices/$(basename "${img%.*}").pdf"
          done

      - name: Generate Master PDF
        run: |
          pandoc combined.md \
            -s \
            --pdf-engine=xelatex \
            --toc \
            --metadata title="Documentation" \
            -o pdf/documentation.pdf

      - name: Generate HTML version
        run: |
          pandoc combined.md \
            -s \
            --toc \
            --metadata title="Documentation" \
            -o site/index.html

          # Ajouter lien vers le PDF
          echo "<p><a href='documentation.pdf' download>Télécharger le PDF complet</a></p>" >> site/index.html

      - name: Copy PDF to site
        run: |
          cp pdf/documentation.pdf site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
