name: Documentation

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra imagemagick

      - name: Prepare directories
        run: |
          mkdir -p pdf

      - name: Convert individual markdown files to PDFs
        run: |
          find docs/ -name '*.md' | while read file; do
            relpath="${file#docs/}"
            filename="${relpath//\//_}"
            filename="${filename%.md}"
            pandoc "$file" \
              -s \
              --pdf-engine=xelatex \
              --template=docs/latex/azure-mui-template.tex \
              -o "pdf/$filename.pdf"
          done

      - name: Convert PNG images to PDF (appendices)
        run: |
          mkdir -p pdf/appendices
          find docs/ -type f \( -iname "*.png" -o -iname "*.jpg" \) | while read img; do
            outname=$(basename "$img")
            convert "$img" "pdf/appendices/${outname%.*}.pdf"
          done

      - name: Create combined.md in desired order
        run: |
          echo "" > combined.md

          # 1. Briefs
          cat docs/brief_part1.md >> combined.md
          echo "\newpage" >> combined.md
          cat docs/brief_part2.md >> combined.md
          echo "\newpage" >> combined.md

          # 2. Benchmarks
          find docs/benchmark -name '*.md' | sort | while read file; do
            cat "$file" >> combined.md
            echo "\newpage" >> combined.md
          done

          # 3. Architectures
          find docs/architecture -name '*.md' | sort | while read file; do
            cat "$file" >> combined.md
            echo "\newpage" >> combined.md
          done

          # 4. Tech-stack
          [ -f docs/tech-stack.md ] && cat docs/tech-stack.md >> combined.md && echo "\newpage" >> combined.md

          # 5. Remaining .md files
          find docs/ -name '*.md' \
            ! -path 'docs/brief_part1.md' \
            ! -path 'docs/brief_part2.md' \
            ! -path 'docs/benchmark/*' \
            ! -path 'docs/architecture/*' \
            ! -path 'docs/tech-stack.md' \
            | sort | while read file; do
              cat "$file" >> combined.md
              echo "\newpage" >> combined.md
            done

          # 6. Appendices notice
          echo "# Annexes\n\nLes documents suivants sont des annexes visuelles." >> combined.md
          find pdf/appendices -name '*.pdf' | sort >> combined.md

      - name: Generate master PDF with TOC and style
        run: |
          pandoc combined.md \
            -s \
            --pdf-engine=xelatex \
            --template=docs/latex/azure-mui-template.tex \
            --toc \
            --toc-depth=2 \
            --metadata title="Documentation" \
            -o pdf/documentation.pdf

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation PDFs
          path: pdf/
          retention-days: 7
