name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'docs/**.md'
      - 'docs/**.png'
      - 'docs/latex/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin

      - name: Create output folders
        run: mkdir -p pdf temp_md

      - name: Convert all .md files to individual PDFs
        run: |
          find docs/ -name '*.md' | while read file; do
            relpath="${file#docs/}"
            filename="${relpath//\//_}"
            filename="${filename%.md}"
            pandoc "$file" \
              -H docs/latex/header.tex \
              --pdf-engine=xelatex \
              --template=docs/latex/azure-mui-template.tex \
              -o "pdf/$filename.pdf"
          done

      - name: Generate combined.md with ordered content
        run: |
          echo "" > combined.md

          # Ordre manuel
          files=(
            "docs/brief/brief1.md"
            "docs/brief/brief2.md"
            "docs/benchmark/benchmark.md"
            "docs/architectures/architecture.md"
            "docs/tech-stack.md"
          )

          # Ajouter les fichiers à combined.md avec saut de page
          for f in "${files[@]}"; do
            [ -f "$f" ] && echo -e "\n\\newpage\n" >> combined.md && cat "$f" >> combined.md
          done

          # Ajouter le reste des fichiers .md triés (hors déjà ajoutés)
          find docs/ -name '*.md' | sort | while read f; do
            if ! grep -q "$f" <<< "${files[*]}"; then
              echo -e "\n\\newpage\n" >> combined.md
              cat "$f" >> combined.md
            fi
          done

          # Ajouter annexe des images (converties en PDF)
          echo -e "\n\\newpage\n# Annexes\n" >> combined.md
          for img in $(find docs/ressources -name '*.png'); do
            name=$(basename "$img")
            echo -e "![${name}](${img})\n" >> combined.md
          done

      - name: Convert combined.md to master PDF
        run: |
          pandoc combined.md \
            -H docs/latex/header.tex \
            --pdf-engine=xelatex \
            --template=docs/latex/azure-mui-template.tex \
            --toc \
            --toc-depth=2 \
            --metadata title="Documentation" \
            -o pdf/documentation.pdf

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: pdf/
          retention-days: 7